AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role - SnowCloudDiscovery with required discovery permissions

Resources:
  SnowCloudDiscoveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SnowCloudDiscovery
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com  
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SnowCloudDiscoveryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: PermissionsNeededForDiscovery
                Effect: Allow
                Action:
                  - account:ListRegions
                  - apigateway:GET
                  - application-autoscaling:Describe*
                  - autoscaling-plans:Describe*
                  - autoscaling:Describe*
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeLaunchConfigurations
                  - cloudformation:Describe*
                  - cloudformation:DescribeStack*
                  - cloudformation:List*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - config:ListDiscoveredResources
                  - dynamodb:Describe*
                  - dynamodb:DescribeTable
                  - dynamodb:ListGlobalTables
                  - dynamodb:ListTables
                  - ec2:Describe*
                  - ec2:ReportInstanceStatus
                  - ecs:Describe*
                  - ecs:List*
                  - eks:Describe*
                  - eks:List*
                  - elasticache:Describe*
                  - elasticache:List*
                  - elasticfilesystem:Describe*
                  - elasticloadbalancing:Describe*
                  - lambda:Get*
                  - lambda:List*
                  - organizations:Describe*
                  - organizations:DescribeOrganization
                  - organizations:List*
                  - rds:Describe*
                  - redshift:Describe*
                  - route53:GetHostedZone
                  - route53:List*
                  - s3:GetAccountPublicAccessBlock
                  - s3:GetBucket*
                  - s3:GetBucketLocation
                  - s3:List*
                  - sdb:GetAttributes
                  - sns:GetEndpointAttributes
                  - sns:GetSubscriptionAttributes
                  - sns:List*
                  - sns:ListPlatformApplications
                  - sns:ListSubscriptions
                  - sns:ListSubscriptionsByTopic
                  - sns:ListTopics
                Resource: "*"
Outputs:
  SnowCloudDiscoveryRoleArn:
    Description: ARN of the SnowCloudDiscovery IAM Role
    Value: !GetAtt SnowCloudDiscoveryRole.Arn
